server:
  port: 9030
spring:
  application:
    name: "Payments"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
#  cloud:
#    stream:
#      bindings:
#        orderCreated-out-0:
#          destination: order-created
#        paymentConfirmed-out-0:
#          destination: payment-confirmed
#      kafka:
#        binder:
#          brokers: localhost:9092

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "Payments"
    description: "eCommerce Payments service"
    version: "1.0.0"

stripe:
  secret-key : ${STRIPE_SECRET_KEY}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY}