CREATE TABLE IF NOT EXISTS Payment (
    payment_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT NOT NULL,
    amount DOUBLE NOT NULL,
    payment_method VARCHAR(50) NOT NULL, -- e.g., CREDIT_CARD, PAYPAL
    status VARCHAR(50) NOT NULL, -- e.g., SUCCESS, FAILED
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
