CREATE TABLE IF NOT EXISTS CATEGORY (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL,
    parent_category_id BIGINT,
    FOREIGN KEY (parent_category_id) REFERENCES CATEGORY(category_id)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    price DOUBLE,
    stock_quantity INT,
    category_id BIGINT,
    FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id)
);
