CREATE TABLE IF NOT EXISTS Cart (
  cart_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS Cart_Item (
   cart_item_id BIGINT AUTO_INCREMENT PRIMARY KEY,
   product_id BIGINT NOT NULL,
   quantity INT NOT NULL,
   cart_id BIGINT NOT NULL,
   CONSTRAINT fk_cart FOREIGN KEY (cart_id) REFERENCES Cart(cart_id) ON DELETE CASCADE
);
